// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {internal} from '../models';

export function CreateTask(arg1:internal.Tasks):Promise<void>;

export function DeleteTask(arg1:number):Promise<void>;

export function GetByID(arg1:number):Promise<internal.Tasks>;

export function GetTasks():Promise<Array<internal.Tasks>>;

export function UpdateTask(arg1:internal.PartialTask):Promise<void>;
