// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTask(arg1) {
  return window['go']['tasks']['Repository']['CreateTask'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['tasks']['Repository']['DeleteTask'](arg1);
}

export function GetByID(arg1) {
  return window['go']['tasks']['Repository']['GetByID'](arg1);
}

export function GetTasks() {
  return window['go']['tasks']['Repository']['GetTasks']();
}

export function UpdateTask(arg1) {
  return window['go']['tasks']['Repository']['UpdateTask'](arg1);
}
